public class Address {
    public void homeAddress(){
        string myName= 'Amy Guney';
        integer totalNumberOfMembers= 5;
        string houseName= 'Guney residence';
        integer houseNumber= 3022;
        string streetName= 'Blantyre';
        string cityName= 'Austin';
        string stateName= 'Texas';
        string stateISOCode= 'US-TX';
        string countryName= 'United States';
        string countryISOCode= 'USA';
        integer zipCode= 78664;
        boolean isThisMyCurrentHomeOrNot= true;

        system.debug(myName);
        system.debug(totalNumberOfMembers);
        system.debug(houseName);
        system.debug(houseNumber);
        system.debug(streetName);
        system.debug(cityName);
        system.debug(stateName);
        system.debug(stateISOCode);
        system.debug(countryName);
        system.debug(countryISOCode);
        system.debug(zipCode);
        system.debug(isThisMyCurrentHomeOrNot);
    }
}
